### ISSUE TITLE
cheap-life is not a good name for this repo

### ISSUE THREAD

**Issue by bridgethillyer** [ClojureBridge/global-growth#2]
I named it cheap-life when I had a different idea of what it would do. I'm horrible at naming things. Any ideas? Global Indicators? World Bank Data Analyzer?

**Comment by bridgethillyer** [comment]
Global Exploration?

**Comment by bridgethillyer** [comment]
I'm going to change the name to global-growth. Any objections?

**Comment by cndreisbach** [comment]
Sounds fine to me.
